<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>false</SelfContained>
    <IncludeAllContentInSingleFile>true</IncludeAllContentInSingleFile>
    <AssemblyTitle>Mouse Position Reset</AssemblyTitle>
    <Product>Mouse Position Reset</Product>
    <Company>Mouse Position Reset</Company>
    <Description>Mouse Position Reset</Description>
    <Version>0.4.0</Version>
    <AssemblyVersion>0.4.0.0</AssemblyVersion>
    <FileVersion>0.4.0.0</FileVersion>
    <InformationalVersion>0.4</InformationalVersion>
    <PackageIcon>cursor.png</PackageIcon>
    <ApplicationIcon>cursor.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="cursor.ico" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\cursor.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Management" Version="10.0.9" />
  </ItemGroup>

</Project>
